name: FootBot Discord

on:
  push:
    branches: "main"

jobs:
  setup:
    runs-on:
      labels: discord-bot

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

  deploy:
    needs: setup
    runs-on:
      labels: discord-bot
    steps:
      - name: Update config.json LINUX
        if: runner.os == 'Linux'
        run: |
          sed -i "s/DISCORD_TOKEN/${{ secrets.DISCORD_TOKEN }}/g" config.json
          sed -i "s/GUILD_ID/${{ secrets.GUILD_ID }}/g" config.json
          sed -i "s/CLIENT_ID/${{ secrets.CLIENT_ID }}/g" config.json
      - name: Update config.json WINDOWS
        if: runner.os == 'Windows'
        run: |
          (Get-Content config.json).Replace("DISCORD_TOKEN","${{ secrets.DISCORD_TOKEN }}") | Set-Content config.json
          (Get-Content config.json).Replace("GUILD_ID","${{ secrets.GUILD_ID }}") | Set-Content config.json
          (Get-Content config.json).Replace("CLIENT_ID","${{ secrets.CLIENT_ID }}") | Set-Content config.json

      - name: Deploy bot LINUX
        if: runner.os == 'Linux'
        run: RUNNER_TRACKING_ID="" && (nohup node index.js &)
      - name: Deploy bot WINDOWS
        shell: bash
        if: runner.os == 'Windows'
        run: RUNNER_TRACKING_ID="" && (nohup node index.js &)